mkdir c:\github
winget install --id=Git.Git -e --accept-package-agreements --accept-source-agreements
winget install --id=Microsoft.VisualStudioCode -e  
winget install --id=AgileBits.1Password -e
winget install --id=7zip.7zip -e
winget install --id=Twilio.Authy -e
winget install --id=Bethesda.Launcher -e 
winget install --id=Microsoft.Bicep -e  
winget install --id=Microsoft.bitsmanager -e  
winget install --id=BrutalChess.BrutalChess -e  
winget install --id=TechSmith.Camtasia -e  
winget install --id=code52.Carnac -e  
winget install --id=Docker.DockerDesktop -e  
winget install --id=joncampbell123.DOSBox-X -e 
winget install --id=JGraph.Draw -e  
winget install --id=Dropbox.Dropbox -e  
winget install --id=ElectronicArts.EADesktop -e  
# winget install --id=File-New-Project.EarTrumpet -e  
# winget install --id=Elgato.ControlCenter -e  
# winget install --id=Elgato.StreamDeck -e  
# winget install --id=EpicGames.EpicGamesLauncher -e  
# winget install --id=Figma.Figma -e  
winget install --id=TimKosse.FileZilla.Client -e  
# winget install --id=BlastApps.FluentSearch -e  
winget install --id=Microsoft.GitCredentialManagerCore -e  
winget install --id=GitHub.cli -e  
# winget install --id=GitHub.GitHubDesktop -e  
# winget install --id=GNU.MidnightCommander -e  
# winget install --id=Google.Chrome -e  
# winget install --id=Greenshot.Greenshot -e  
winget install --id=icsharpcode.ILSpy -e  
winget install --id=LINQPad.LINQPad.7 -e  
winget install --id=WestWind.MarkdownMonster -e  
winget install --id=Microsoft.dotnet -e  
winget install --id=Microsoft.Teams -e  
# winget install --id=Mono.Mono -e  
winget install --id=OpenJS.NodeJS.LTS -e  
# winget install --id=OBSProject.OBSStudio -e  
winget install --id=JanDeDobbeleer.OhMyPosh -e  
# winget install --id=Microsoft.PowerAutomateDesktop -e  
winget install --id=Microsoft.PowerShell -e  
winget install --id=Microsoft.PowerToys -e  
winget install --id=Python.Python.3 -e  
winget install --id=Microsoft.RemoteDesktopClient -e  
# winget install --id=RubyInstallerTeam.Ruby -e  
# winget install --id=NickeManarin.ScreenToGif -e  
winget install --id=ScummVM.ScummVM -e  
# winget install --id=OpenWhisperSystems.Signal -e
# winget install --id=Spotify.Spotify -e  
# winget install --id=Microsoft.SurfaceDuoEmulator.Android11 -e  
# winget install --id=tailscale.tailscale -e  
winget install --id=CodeSector.TeraCopy -e  
# winget install --id=TorProject.TorBrowser -e  
# winget install --id=Canonical.Ubuntu -e  
# winget install --id=dorssel.usbipd-win -e  
# winget install --id=Microsoft.VisualStudio.2022.Community -e  
# winget install --id=VideoLAN.VLC -e  
winget install --id=RealVNC.VNCViewer -e  
# winget install --id=WhatsApp.WhatsApp -e  
# winget install --id=WinMerge.WinMerge -e  
winget install --id=Yarn.Yarn -e 